#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=40:00:00
#PBS -N gatk_geno_GVCFs
#PBS -m abe
#PBS -M cxb585@psu.edu
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

working_dir=$PBS_O_WORKDIR

module load gatk

GENOME_FA=genomes/rheMac2/rheMac2.fa
GENOME_NAME=rhesus

# ------------------------------------------------------------------------------
# Run program
# ------------------------------------------------------------------------------

cd $working_dir

if [ "$PBS_ARRAYID" -eq 21 ]; then
	CHROM=chrX
else
	CHROM=chr$PBS_ARRAYID
fi

# Make output directory
mkdir -p ${GENOME_NAME}_snps

java -Xmx96g -jar ${GATK}/gatk-package-4.1.4.0-local.jar \
    GenotypeGVCFs \
    -R $GENOME_FA \
    -V gendb://${GENOME_NAME}_snps_$CHROM \
    -O ${GENOME_NAME}_snps/${CHROM}.raw.snps.indels.vcf \
    -L ${CHROM}

exit;
