#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=30:00:00
#PBS -N ngs-map-make
#PBS -M cxb585@psu.edu
#PBS -m abe
#PBS -e localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.e${PBS_JOBID}.${PBS_ARRAYID}
#PBS -o localhost:${PBS_O_WORKDIR}/${PBS_JOBNAME}.o${PBS_JOBID}.${PBS_ARRAYID}

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

# Call with qsub -t 1-${NUM_INDIVIDUALS} call_make.pbs

working_dir=$PBS_O_WORKDIR

module load fastqc/0.11.5
module load fastx/0.0.13
module load bwa/0.7.16a
module load samtools/1.5
module load bedtools/2.26.0
module load kent/302
module load picard/2.10.10
module load bamtools/2.4.1
module load gatk/3.8
module load bcftools/1.5
module load vcftools/0.1.15
module load tabix/1.5
module load plink/1.9

# ------------------------------------------------------------------------------
# Run pipeline
# ------------------------------------------------------------------------------

cd $working_dir

THIS_IND=`awk "NR==$PBS_ARRAYID" data/individual_list.txt`

echo "Starting Make for individual $THIS_IND";

# To just test:
# make --just-print -s -f full_analysis.mk indiv IND_ID=${THIS_IND}

make -s -f full_analysis.mk indiv IND_ID=${THIS_IND}

echo "Finished Make";

exit;
