#!/bin/bash

#$ -N ngs-map-make
#$ -M cbergey@nd.edu
#$ -m abe
#$ -q *@@bio
#$ -pe smp 8

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

working_dir=$SGE_O_WORKDIR

# ------------------------------------------------------------------------------
# Run pipeline
# ------------------------------------------------------------------------------

cd $working_dir

THIS_IND=ssese$SGE_TASK_ID

echo "Starting Make for individual $THIS_IND";

# To just test:
# make --just-print -s -f full_analysis.mk indiv IND_ID=${THIS_IND}

module load bio/fastqc/0.11.2 
module load bio/bwa/0.6.2
module load bio/samtools/1.2
module load bio/picardtools/1.119 
module load bio/gatk/3.3 
module load plink

make -s -f full_analysis.mk indiv IND_ID=${THIS_IND}

echo "Finished Make";

exit;
